# Generated by Django 4.2.6 on 2023-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_alter_ad_options_alter_comment_options_ad_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ads/img"),
        ),
    ]
